# Generated by Django 4.0.4 on 2022-05-24 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind', models.FloatField()),
                ('pressure', models.FloatField()),
                ('water', models.FloatField()),
                ('datetimeonfarm', models.DateTimeField(default=datetime.datetime(2022, 5, 24, 8, 9, 56, 379019, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.FloatField()),
                ('width', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('gps', models.CharField(max_length=50)),
                ('farm_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm.farmstatus')),
            ],
        ),
    ]
