# Generated by Django 4.0.4 on 2022-05-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0002_remove_farminformation_farm_status_delete_vegetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind', models.FloatField()),
                ('pressure', models.FloatField()),
                ('water', models.FloatField()),
                ('datetimeonfarm', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VegetableStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.FloatField()),
                ('width', models.FloatField()),
                ('leaf', models.BooleanField(default=True)),
                ('datetimegrowth', models.DateTimeField()),
                ('image', models.FileField(default=False, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VegetableTimeLapseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetablename', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=40)),
                ('qualiative', models.TextField()),
                ('vegetableStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.vegetablestatus')),
            ],
        ),
        migrations.CreateModel(
            name='FarmInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('gps', models.CharField(max_length=50)),
                ('farmstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmstatus')),
            ],
        ),
    ]
