# Generated by Django 4.0.4 on 2022-05-30 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farminformation',
            name='farmstatus',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='vegetableStatus',
        ),
        migrations.AddField(
            model_name='farmstatus',
            name='farminfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmstatus', to='farm.farminformation'),
        ),
        migrations.AddField(
            model_name='vegetablestatus',
            name='vegetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vegetale', to='farm.vegetable'),
        ),
    ]
