# Generated by Django 4.0.4 on 2022-05-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_remove_farminformation_farmstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetablestatus',
            name='image',
            field=models.FileField(default='1.png', upload_to='veget_pic'),
        ),
        migrations.AlterField(
            model_name='vegetablestatus',
            name='vegetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vegetable', to='farm.vegetable'),
        ),
    ]
