# Generated by Django 4.0.6 on 2022-10-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_alter_vegetablestatus_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetablestatus',
            name='image',
            field=models.FileField(default='veget_pic/1.png', upload_to='veget_pic'),
        ),
    ]
