# Generated by Django 4.0.6 on 2022-10-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_alter_vegetablestatus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlButtonInFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomp1', models.BooleanField()),
                ('pomp2', models.BooleanField()),
                ('servor1', models.BooleanField()),
                ('servor2', models.BooleanField()),
                ('fan1', models.BooleanField()),
                ('fan2', models.BooleanField()),
            ],
        ),
    ]
