# Generated by Django 4.0.6 on 2022-10-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_controlbuttoninfarm_saveenergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlbuttoninfarm',
            name='test_fields',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
