# Generated by Django 4.0.6 on 2022-11-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_testcam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcam',
            name='frame_buf',
            field=models.TextField(default=b'abc'),
        ),
    ]
