# Generated by Django 4.0.6 on 2022-11-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_testcam_height_testcam_length_testcam_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcam',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testcam',
            name='length',
            field=models.IntegerField(null=None),
        ),
        migrations.AlterField(
            model_name='testcam',
            name='width',
            field=models.IntegerField(null=None),
        ),
    ]
