# Generated by Django 4.0.6 on 2022-11-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_alter_testcam_height_alter_testcam_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcam',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcam',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testcam',
            name='width',
            field=models.IntegerField(),
        ),
    ]
