# Generated by Django 4.0.6 on 2022-11-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_alter_testcam_height_alter_testcam_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcam',
            name='height',
        ),
        migrations.RemoveField(
            model_name='testcam',
            name='length',
        ),
        migrations.RemoveField(
            model_name='testcam',
            name='width',
        ),
    ]
