# Generated by Django 4.0.6 on 2022-11-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_remove_testcam_height_remove_testcam_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcam',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcam',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcam',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
