# Generated by Django 4.0.6 on 2022-11-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_testcam_height_testcam_length_testcam_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcam',
            old_name='length',
            new_name='lenght',
        ),
    ]
