# Generated by Django 4.0.6 on 2022-11-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_rename_length_testcam_lenght'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcam',
            name='veget',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='testcam',
            name='height',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='testcam',
            name='width',
            field=models.IntegerField(default=320),
        ),
    ]
