# Generated by Django 3.2.9 on 2022-12-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_testcam_veget_alter_testcam_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcam',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testcam',
            name='lenght',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testcam',
            name='width',
            field=models.IntegerField(),
        ),
    ]
