# Generated by Django 4.1.3 on 2022-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_auto_20221215_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcam',
            name='height',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='testcam',
            name='lenght',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testcam',
            name='width',
            field=models.IntegerField(default=320),
        ),
    ]
